# Generated by Django 5.2.14 on 2026-07-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0010_cohort_bfr_observed_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortbackfillrun",
            name="marker_watch",
            field=models.JSONField(
                blank=True,
                help_text='Opaque watcher resume state written by the Rust seeder, shape {"schema":2,"topic":"...","positions":{...},"ends":{...}|null}. Django never interprets it.',
                null=True,
            ),
        ),
    ]
