# Generated by Django 5.2.14 on 2026-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('tasks', '0077_taskartifact_export_asset_id')]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='slack_thread_target',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
